### ISSUE TITLE
build fail : missing system_error

### ISSUE THREAD

**Issue by moonshaadow** [bondagit/aes67-linux-daemon#33]
Hi there.
I'm unable to build on Ubuntu 18.04 ( ubuntu studio low latency + KX studio repos)

```
[  5%] Building CXX object CMakeFiles/aes67-daemon.dir/error_code.cpp.o
In file included from /home/studio/Bureau/aes67-linux-daemon/daemon/error_code.cpp:20:
/home/studio/Bureau/aes67-linux-daemon/daemon/error_code.hpp:23:10: fatal error: 'system_error' file not found
#include <system_error>
         ^~~~~~~~~~~~~~
1 error generated.
CMakeFiles/aes67-daemon.dir/build.make:62: recipe for target 'CMakeFiles/aes67-daemon.dir/error_code.cpp.o' failed
make[2]: *** [CMakeFiles/aes67-daemon.dir/error_code.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/aes67-daemon.dir/all' failed
make[1]: *** [CMakeFiles/aes67-daemon.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```
I've used ubuntu-packages.sh, so dependencies should be ok.

**Comment by bondagit** [comment]
This is part of the Boost System library. That should be at version 1_65 for your distro.
See: https://www.boost.org/doc/libs/1_65_0/libs/system/doc/index.html

The file should be located in:
/usr/include/boost/system/system_error.hpp

And it should be included by:
> sudo apt-get install -y libboost-all-dev

**Comment by moonshaadow** [comment]
I've got the Boost library in the right place.
It seems to be a Clang related problem :
I can change the issue creating a system_error link in `/usr/lib/clang/6.0/include/` and pointing to `/usr/include/boost/system/system_error.hpp`, but it just give me another error.

What can I do to tell to clang to look into the correct path?

**Comment by bondagit** [comment]
You can look into the _build.sh_ script.
I can compile with clang using the following commands:

```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
export TOPDIR=$(pwd)
cd daemon
cmake -DCPP_HTTPLIB_DIR="$TOPDIR"/3rdparty/cpp-httplib -DRAVENNA_ALSA_LKM_DIR="$TOPDIR"/3rdparty/ravenna-alsa-lkm -DENABLE_TESTS=ON -DWITH_AVAHI=ON .
make
```

**Comment by bondagit** [comment]
Any upstate on this issue?

**Comment by moonshaadow** [comment]
I'm able to build without Clang. 
I have issues trying to use the driver, but I could tell you more only in a week...
