### ISSUE TITLE
ravenna driver no longer compiles with kernel 6.12.3

### ISSUE THREAD

**Issue by ccaudle** [bondagit/aes67-linux-daemon#187]
After updating to kernel 6.12.3 the Merging ravenna driver no longer builds.  It seems one of the malloc function names has changed, or the function has been replaced by a new function.
The driver from the Merging repository does build (although with a lot of warnings, the code is not very clean with the recent gcc default warning settings).

make -C /lib/modules/6.12.3-200.fc41.x86_64/build/ M=/home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver modules
make[1]: Entering directory '/usr/src/kernels/6.12.3-200.fc41.x86_64'
  CC [M]  /home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/c_wrapper_lib.o
  CC [M]  /home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/audio_driver.o
/home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/audio_driver.c: In function ‘mr_alsa_audio_pcm_hw_params’:
/home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/audio_driver.c:1384:11: error: implicit declaration of function ‘snd_pcm_lib_alloc_vmalloc_buffer’ [-Wimplicit-function-declaration]
 1384 |     err = snd_pcm_lib_alloc_vmalloc_buffer(substream, bufferBytes);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/audio_driver.c: In function ‘mr_alsa_audio_pcm_hw_free’:
/home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/audio_driver.c:1411:19: error: implicit declaration of function ‘snd_pcm_lib_free_vmalloc_buffer’; did you mean ‘snd_pcm_lib_malloc_pages’? [-Wimplicit-function-declaration]
 1411 |             err = snd_pcm_lib_free_vmalloc_buffer(substream);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   snd_pcm_lib_malloc_pages
/home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/audio_driver.c: At top level:
/home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/audio_driver.c:1857:17: error: ‘snd_pcm_lib_get_vmalloc_page’ undeclared here (not in a function); did you mean ‘snd_pcm_lib_malloc_pages’?
 1857 |     .page =     snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 snd_pcm_lib_malloc_pages
make[3]: *** [scripts/Makefile.build:229: /home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/audio_driver.o] Error 1
make[2]: *** [/usr/src/kernels/6.12.3-200.fc41.x86_64/Makefile:1976: /home/chris/Src/Ravenna/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver] Error 2
make[1]: *** [Makefile:236: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.12.3-200.fc41.x86_64'
make: *** [Makefile:15: modules] Error 2

**Comment by bondagit** [comment]
yes, we have to switch to the new managed buffer allocation API, old special vmalloc-specific allocation and page handling were dropped starting from kernel v6.12.
This is a duplicate of:  https://github.com/bondagit/ravenna-alsa-lkm/issues/29

**Comment by ccaudle** [comment]
Is the updated version available somewhere?  The build.sh script has the git submodule update command since a few months now, and also I checked github code and the last change to audio_driver.c was in  September, but this compilation failure only started this week with kernel 6.12.3 (compiled OK with 6.12.1).

**Comment by bondagit** [comment]
no, it's not available yet
