### ISSUE TITLE
Compilation error Ubuntu 22.04: Could NOT find Boost

### ISSUE THREAD

**Issue by helmet21** [bondagit/aes67-linux-daemon#104]
Installing with build.sh script on Ubuntu 22.04 I get this error:

> Could NOT find Boost (missing: system thread log program_options) (found version "1.74.0")

I tested on Ubuntu 20.04 after installing Boost with

> sudo apt install libboost-all-dev

and the error was fixed. I guess that the compilation breaks with version 1.74.0 but works with 1.71.0 which is the one provided for Ubuntu 20.04.
FYI: After this I needed libavahi-client-dev to finally make the compilation successful.

> sudo apt install libavahi-client-dev

Maybe it will work on Ubuntu 22.04 if you downgrade libboost but I haven't tried that.
