### ISSUE TITLE
Compilation error on 5.4.19-rt11 realtime kernel

### ISSUE THREAD

**Issue by hifi25nl** [bondagit/aes67-linux-daemon#2]
Trying to compile on 5.4.19-rt11 realtime kernel on archlinux:
gcc version 9.2.1+20200130-2
I have an error about undefined named operand ‘new’
------------
make -C /lib/modules/5.4.19-rt11-1-rt/build/ M=/media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver modules
make[1]: Entering directory '/usr/lib/modules/5.4.19-rt11-1-rt/build'
  CC [M]  /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/c_wrapper_lib.o
In file included from ./include/linux/atomic.h:7,
                 from ./include/linux/jump_label.h:249,
                 from ./arch/x86/include/asm/string_64.h:6,
                 from ./arch/x86/include/asm/string.h:5,
                 from ./include/linux/string.h:20,
                 from /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/MTAL_stdint.h:68,
                 from /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/c_wrapper_lib.h:35,
                 from /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/c_wrapper_lib.c:32:
./arch/x86/include/asm/atomic.h: In function ‘arch_atomic_try_cmpxchg’:
./arch/x86/include/asm/atomic.h:200:2: error: undefined named operand ‘new’
  200 |  return try_cmpxchg(&v->counter, old, new);
      |  ^~~~~~
./arch/x86/include/asm/atomic.h:200:2: error: undefined named operand ‘new’
./arch/x86/include/asm/atomic.h:200:2: error: undefined named operand ‘new’
./arch/x86/include/asm/atomic.h:200:2: error: undefined named operand ‘new’
In file included from ./arch/x86/include/asm/atomic.h:262,
                 from ./include/linux/atomic.h:7,
                 from ./include/linux/jump_label.h:249,
                 from ./arch/x86/include/asm/string_64.h:6,
                 from ./arch/x86/include/asm/string.h:5,
                 from ./include/linux/string.h:20,
                 from /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/MTAL_stdint.h:68,
                 from /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/c_wrapper_lib.h:35,
                 from /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/c_wrapper_lib.c:32:
./arch/x86/include/asm/atomic64_64.h: In function ‘arch_atomic64_try_cmpxchg’:
./arch/x86/include/asm/atomic64_64.h:186:2: error: undefined named operand ‘new’
  186 |  return try_cmpxchg(&v->counter, old, new);
      |  ^~~~~~
./arch/x86/include/asm/atomic64_64.h:186:2: error: undefined named operand ‘new’
./arch/x86/include/asm/atomic64_64.h:186:2: error: undefined named operand ‘new’
./arch/x86/include/asm/atomic64_64.h:186:2: error: undefined named operand ‘new’
make[2]: *** [scripts/Makefile.build:266: /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/c_wrapper_lib.o] Error 1
make[1]: *** [Makefile:1652: /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.4.19-rt11-1-rt/build'
make: *** [Makefile:14: modules] Error 2

**Comment by bondagit** [comment]
The problem could be resolved by the enclosed patch. Can you give it a try ? Thanks
[MTAL_stdint.zip](https://github.com/bondagit/aes67-linux-daemon/files/4237241/MTAL_stdint.zip)

**Comment by hifi25nl** [comment]
I have cloned another time and applied all patches including MTAL_stdint.h
I have also verified that this last patch was really applied.

I have still the same error:
/media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/RTP_audio_stream.c:1036:13: warning: unused variable ‘delta’ [-Wunused-variable]
 1036 |     int64_t delta = self->m_tRTPStream.m_ui64LastAudioSampleReceivedSAC - pManager->get_global_SAC(pManager->user);
      |             ^~~~~
  CC [M]  /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/RTP_stream.o
  CC [M]  /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/RTP_stream_info.o
In file included from ./include/linux/atomic.h:7,
                 from ./include/linux/jump_label.h:249,
                 from ./arch/x86/include/asm/string_64.h:6,
                 from ./arch/x86/include/asm/string.h:5,
                 from ./include/linux/string.h:20,
                 from /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/RTP_stream_info.c:36:
./arch/x86/include/asm/atomic.h: In function ‘arch_atomic_try_cmpxchg’:
./arch/x86/include/asm/atomic.h:200:2: error: undefined named operand ‘new’
  200 |  return try_cmpxchg(&v->counter, old, new);
      |  ^~~~~~
./arch/x86/include/asm/atomic.h:200:2: error: undefined named operand ‘new’
./arch/x86/include/asm/atomic.h:200:2: error: undefined named operand ‘new’
./arch/x86/include/asm/atomic.h:200:2: error: undefined named operand ‘new’
In file included from ./arch/x86/include/asm/atomic.h:262,
                 from ./include/linux/atomic.h:7,
                 from ./include/linux/jump_label.h:249,
                 from ./arch/x86/include/asm/string_64.h:6,
                 from ./arch/x86/include/asm/string.h:5,
                 from ./include/linux/string.h:20,
                 from /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/RTP_stream_info.c:36:
./arch/x86/include/asm/atomic64_64.h: In function ‘arch_atomic64_try_cmpxchg’:
./arch/x86/include/asm/atomic64_64.h:186:2: error: undefined named operand ‘new’
  186 |  return try_cmpxchg(&v->counter, old, new);
      |  ^~~~~~
./arch/x86/include/asm/atomic64_64.h:186:2: error: undefined named operand ‘new’
./arch/x86/include/asm/atomic64_64.h:186:2: error: undefined named operand ‘new’
./arch/x86/include/asm/atomic64_64.h:186:2: error: undefined named operand ‘new’
make[2]: *** [scripts/Makefile.build:266: /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver/RTP_stream_info.o] Error 1
make[1]: *** [Makefile:1652: /media/linux/Downloads/Temp/Ravenna/ravenna-alsa-lkm/driver] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.4.19-rt11-1-rt/build'
make: *** [Makefile:14: modules] Error 2

**Comment by bondagit** [comment]
Hi, in the last patch I forgot a file. 
Can you please re-try with the enclosed patch ?
This works for me compiling the module with gcc version 7.4.0  for kenerl-5.4.19-rt11 

[ravenna-alsa-lkm-undefined-new.zip](https://github.com/bondagit/aes67-linux-daemon/files/4257914/ravenna-alsa-lkm-undefined-new.zip)

**Comment by bondagit** [comment]
This should be fixed by c62ccdb

**Comment by hifi25nl** [comment]
OK, just compiled fine!

**Comment by bondagit** [comment]
Thanks for the info.
